
datasets:
  - json_path: ${DATA_ROOT}/data_config/emer_rewrite.json
    data_root: ${DATA_ROOT}/videos/videos
    sampling_strategy: end:50%
  - json_path: ${DATA_ROOT}/data_config/social_iq_v2_rewrite.json
    data_root: ${DATA_ROOT}/videos/videos
    sampling_strategy: end:50%
  - json_path: ${DATA_ROOT}/data_config/Video-R1_rewrite.json
    data_root: ${DATA_ROOT}
    sampling_strategy: end:3%
